name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install eigen3
      run: sudo apt-get install libeigen3-dev
    - name: install boost
      run: sudo apt-get install libboost-dev
    - name: cmake
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Wall -Werror" ..
    - name: make
      run: cd build && make
    - name: ctest
      run: cd build && ctest -V
